#--------------------------------FChat-------------------------------#
#                       Plugin by Connor Michalec                    #
######################################################################
######################################################################
#FChat Permissions:                                                  #      
#fchat.chatcolor.use                                                 #
#fchat.chatcolor.colors.<amount of colors>                           #
#fchat.chatcolor.format.bold                                         #
#fchat.chatcolor.format.italic                                       #
#fchat.chatcolor.format.magic                                        #
#fchat.chatcolor.format.underline                                    #
######################################################################
######################################################################
